"""updating habit model

Revision ID: 5951240a9077
Revises: 479941ccd550
Create Date: 2021-06-14 03:02:04.958590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5951240a9077'
down_revision = '479941ccd550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('time', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'time')
    # ### end Alembic commands ###
