"""updating models

Revision ID: d5870afa2b0a
Revises: c4a0686aa35e
Create Date: 2021-06-04 15:48:56.104951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5870afa2b0a'
down_revision = 'c4a0686aa35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'moods', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moods', type_='unique')
    # ### end Alembic commands ###
