"""changed models

Revision ID: 479941ccd550
Revises: d5870afa2b0a
Create Date: 2021-06-07 14:40:53.555351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479941ccd550'
down_revision = 'd5870afa2b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'body',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('observations', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('observations', 'body',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
